import { Category, Product } from './types';

export const categories: Category[] = [
  {
    id: 'industrial-packaging',
    name: 'Industrial Packaging',
    description: 'Heavy-duty packaging solutions for commercial and industrial use.',
    image: '/images/cat-industrial-packaging.jpeg',
    section: 'packaging'
  },
  {
    id: 'sales-growth-automation',
    name: 'Sales & Growth Automation',
    description: 'AI-driven tools to accelerate sales and scale your business.',
    image: '/images/cat-sales-growth.jpeg',
    section: 'ai-solutions'
  },
  {
    id: 'procurement-supply-chain-ai',
    name: 'Procurement & Supply Chain Intelligence',
    description: 'Optimize your supply chain and procurement with AI forecasting and analytics.',
    image: '/images/cat-procurement.jpeg',
    section: 'ai-solutions'
  },
  {
    id: 'content-creative-ai',
    name: 'Content & Creative AI',
    description: 'Generate high-quality content and creative assets powered by AI.',
    image: '/images/img28.jpeg',
    section: 'ai-solutions'
  },
  {
    id: 'customer-experience-support',
    name: 'Customer Experience & Support',
    description: 'Enhance customer satisfaction with intelligent AI support agents.',
    image: '/images/cat-cx-support.jpeg',
    section: 'ai-solutions'
  },
  {
    id: 'knowledge-enterprise-ai',
    name: 'Knowledge & Enterprise AI',
    description: 'Transform business data and documents into intelligent assistants.',
    image: '/images/img14.jpeg',
    section: 'ai-solutions'
  },
  {
    id: 'custom-ai-development',
    name: 'Custom AI Development',
    description: 'Bespoke AI solutions built perfectly to your unique requirements.',
    image: '/images/img23.jpeg',
    section: 'ai-solutions'
  },
  // Electronics Categories
  {
    id: 'electronics-gaming-pc',
    name: 'AI Gaming PCs',
    description: 'High-performance gaming desktops with NVIDIA AI technology and Kalika optimization.',
    image: '/images/img15.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-workstation-pc',
    name: 'AI Workstations',
    description: 'Professional workstations for content creation, AI/ML, and enterprise workflows.',
    image: '/images/img20.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-budget-pc',
    name: 'Budget AI PCs',
    description: 'Affordable AI-powered desktops for everyday computing and entry-level gaming.',
    image: '/images/img15.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-gpu',
    name: 'NVIDIA GPUs',
    description: 'Graphics cards with AI upscaling, ray tracing, and neural rendering.',
    image: '/images/img15.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-camera',
    name: 'AI Camera Systems',
    description: 'Professional cameras with AI auto-focus, scene detection, and smart features.',
    image: '/images/img18.jpg',
    section: 'electronics'
  },
  {
    id: 'electronics-security',
    name: 'AI Security Systems',
    description: 'Smart surveillance with AI detection, facial recognition, and automated alerts.',
    image: '/images/img8.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-webcam',
    name: 'AI Webcams',
    description: 'Streaming webcams with AI background blur, auto-framing, and noise cancellation.',
    image: '/images/img2.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-monitor',
    name: 'AI Gaming Monitors',
    description: 'Premium displays with AI upscaling, smart HDR, and eye care technology.',
    image: '/images/img15.jpeg',
    section: 'electronics'
  },
  {
    id: 'electronics-ai-bundle',
    name: 'AI Smart Bundles',
    description: 'Complete AI-powered setups combining PC, camera, and monitor at bundle discounts.',
    image: '/images/img20.jpeg',
    section: 'electronics'
  }
];

export const products: Product[] = [
  // Industrial Packaging
  {
    id: 'p-stretch-film',
    name: 'Industrial Stretch Film',
    description: 'High-strength stretch film for secure pallet wrapping. Available in manual, machine, and pre-stretched formats.',
    longDescription: "**Stretch film specs** cover material (LLDPE, LDPE), dimensions (thickness, width, length), performance (tensile strength, elongation, cling), and type (manual/hand, machine, pre-stretched, colored, VCI) for securing pallets/products, with key parameters like micron thickness (8-35µm), width (100-600mm), elongation (300-400%), and strength varying by grade for different applications.\n\n**Key Specifications**\n* **Material**: Primarily Linear Low-Density Polyethylene (LLDPE), sometimes blended with LDPE or cast/blown for specific properties.\n* **Type**:\n   * *Manual/Hand*: For lower volume, uses handheld dispensers (e.g., 18µm, 300% elongation).\n   * *Machine*: For high-speed pallet wrappers, stronger (e.g., 1.5kg/25mm strength, 400% elongation).\n   * *Pre-Stretched*: Thinner, already stretched for efficient application.\n   * *Specialty*: Colored (black, blue, green), VCI (for metals), or UV-resistant.\n* **Dimensions**: Thickness (8-35µm), Width (100-600mm), Length (100-1500m).\n* **Performance Metrics**:\n   * *Tensile Strength*: Measures resistance to breaking (e.g., 1-1.5 kg/25mm).\n   * *Elongation*: Ability to stretch (e.g., 300-400%).\n   * *Cling*: One-sided or two-sided (inner/outer).\n   * *Tear Resistance*: Elmendorf tear strength (e.g., 400-500 GMS/Sht MD/TD).\n* **Appearance**: Uniform, transparent (unless colored), free from defects like holes, streaks, or gels.\n* **Core**: Paper core sizes (e.g., 76mm or 3-inch ID).\n\n* **General Palletizing**: Standard LLDPE, 17-23µm thickness, good elongation and strength for unitizing loads.\n* **Heavy/Pointy Loads**: Blown film with higher tear resistance.\n* **Food/Pharma**: High clarity, possibly VCI for metal parts.",
    price: 45.99,
    categoryId: 'industrial-packaging',
    images: ['/images/stretch-film-new.png'],
    rating: 4.8,
    isFeatured: true,
    features: ['8-35µm thickness', '300-400% elongation', 'Tear resistant (400-500 GMS/Sht)', 'High tensile strength (1-1.5 kg/25mm)'],
    moq: 300,
    uom: 'KGM',
    reviews: [
      { id: 'r1', userName: 'John D.', rating: 5, comment: 'Excellent quality for our warehouse.', date: '2023-10-01' },
      { id: 'r1b', userName: 'Priya S.', rating: 4, comment: 'Good roll consistency. Will reorder for our factory.', date: '2024-02-14' },
      { id: 'r1c', userName: 'Mike R.', rating: 5, comment: 'Holds up well for heavy pallet loads. Highly recommended.', date: '2024-05-22' }
    ]
  },
  {
    id: 'p-poly-bag',
    name: 'Polybags (LDPE/LLDPE/HDPE)',
    description: 'Durable polyethylene bags for bulk storage and shipping. Available in flat, gusseted, and wicketed types.',
    longDescription: "A **poly bag's specification** details its material (LDPE, LLDPE, HDPE), dimensions (width, length, gauge/thickness in mils/microns), type (flat, gusseted, wicketed), strength (puncture, tensile, seal), color, and intended use, often adhering to standards like FDA compliance for food contact, with key metrics like density, vapor transmission, and clarity defining performance. Key specs include thickness (e.g., 1-2 mil for light, 4-6 mil for heavy-duty), material (polyethylene types), and dimensional tolerances, crucial for matching the bag to its packaging purpose, from light retail to industrial storage.\n\n**Key Specification Categories**\n* **Material**:\n   * *LDPE (Low-Density Polyethylene)*: Common for general use, flexible.\n   * *LLDPE (Linear Low-Density Polyethylene)*: Offers better tear/puncture resistance.\n   * *HDPE (High-Density Polyethylene)*: Strong, often used for stronger, thinner bags.\n   * *Blends*: Combinations for specific properties.\n* **Dimensions & Thickness (Gauge)**:\n   * *Thickness (Mil/Gauge)*: 1-2 mil (light duty), 3 mil (medium), 4-6+ mil (heavy duty).\n   * *Dimensions*: Width (flat or layflat), Length (L), Gusset (if applicable).\n* **Physical Properties**:\n   * *Tensile Strength (MD/TD)*: Machine Direction vs. Transverse Direction strength (ASTM D882).\n   * *Puncture Resistance*: Ability to resist piercing (e.g., >12 lbs for 3mil).\n   * *Heat Seal Strength*: Seal integrity (e.g., >10 lbs/inch for 3mil).\n   * *Density*: (e.g., 0.92-0.98 g/cm³).\n   * *MVTR (Material Vapor Transmission Rate)*: Moisture barrier quality.\n* **Bag Type/Structure**:\n   * *Flat Bags*: Simple, often side-weld.\n   * *Gusseted*: Expandable sides for volume.\n   * *Wicketed*: Stacked on a wire 'wicket' for automated packing.\n   * *U-Shaped/Vest Type*: For carry/retail.\n* **Additives & Features**:\n   * *Color*: Clear, white, black inner (for privacy).\n   * *Anti-Static*: Prevents static cling.\n   * *Food Grade*: Complies with FDA regulations (21 CFR).\n\n**Example Specification Breakdown (LDPE Bag)**\n* **Material**: LDPE/LLDPE.\n* **Thickness**: 3 mil (± 10%).\n* **Dimensions**: 10\" x 13\" (example).\n* **Puncture Resistance**: ≥ 12 lbs (ASTM D374).\n* **Seal Strength**: ≥ 10 lbs/inch (ASTM D374).\n* **Color**: Clear.\n* **Use**: General packaging, food storage.",
    price: 25.50,
    categoryId: 'industrial-packaging',
    images: ['/images/img13.jpeg'],
    rating: 4.5,
    features: ['1-6 mil thickness', 'Puncture resistant', 'Heat seal strength >10 lbs/inch', 'Different blends available'],
    moq: 30,
    uom: 'KGM',
    reviews: []
  },
  {
    id: 'p-polybox',
    name: 'Industrial Polybox',
    description: 'Heavy-duty foldable PP containers for logistics and compact PC enclosures for sensitive components.',
    longDescription: "\"Poly Box\" is a general term for a container made from a type of plastic resin, typically polypropylene (PP) or polycarbonate (PC). Due to the variety of applications (from small electronic enclosures to large industrial shipping crates), the specifications vary widely based on the intended use.\n\nBelow are specifications for two common types of \"Poly Boxes\":\n\n**Industrial Foldable Container (e.g., for Automobile Parts)**  \nThis type is a heavy-duty, large container designed for logistics and warehousing.\n* **Material**: Polypropylene (PP)\n* **Dimensions**: Typically large, e.g., 1200 x 800 x 950 mm (L x W x H)\n* **Capacity (Volume)**: Around 755 Liters\n* **Weight**: Approx. 30 kg\n* **Load Capacity**:\n  * *Maximum/Static Load*: 4000 kg\n  * *Dynamic Load*: 1200 kg\n  * *Maximum Upload (single use)*: 600 kg\n* **Features**:\n  * Foldable design to save space when empty\n  * Four-way entry for pallet jacks/forklifts\n  * Resistant to acids and temperature variations (-20°C to 45°C)\n  * Washable at up to 90°C\n\n**Electrical/Electronic Enclosure (e.g., Control Box, Terminal Box)**  \nThis type is a smaller, robust, and often weatherproof box used to house sensitive components.\n* **Material**: Polycarbonate (PC) resin, known for high impact resistance\n* **Dimensions**: Wide range of sizes, e.g., 120 x 80 x 75.2 mm (external L x W x H)\n* **Protection Grade (IP Rating)**: Typically IP65, meaning it is dust-tight and protected against water jets\n* **Color**: Often light gray or white-gray, with options for opaque or transparent lids\n* **Operating Temperature Range**: -20°C to +75°C\n* **Features**:\n  * Self-extinguishing (UL94 V-2 standard)\n  * Can include knockouts for wiring\n  * Designed for wall mounting without external legs",
    price: 120.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img15.jpeg'],
    rating: 4.9,
    features: ['Polypropylene (PP) or Polycarbonate (PC)', 'Up to 4000kg static load capacity', 'Foldable design', 'Weatherproof (IP65 options)'],
    moq: 150,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-vci-polybag',
    name: 'VCI Anti-Corrosion Polybags',
    description: 'Special plastic bags with embedded Vapor Corrosion Inhibitors that protect metal parts from rust during storage/shipping.',
    longDescription: "**VCI poly bags** are special plastic bags with embedded Vapor Corrosion Inhibitors that protect metal parts from rust/corrosion during storage/shipping by releasing protective molecules, available in custom sizes, colors (blue/yellow/clear), thicknesses (75-500 microns), and formats (bags, sheets, rolls), offering high strength, water resistance, and anti-corrosion properties for various industries. Key specs include thickness, dimensions (width x length), material (VCI additives), and physical properties like tensile strength and tear resistance, with custom printing often available.\n\n**Key Product Specifications**:\n* **Material**: Polyethylene film with integrated VCI chemicals.\n* **Protection**: Inhibits corrosion on ferrous and non-ferrous metals by forming a protective layer, preventing rust from moisture/oxygen.\n* **Thickness**: Typically ranges from 75 to 500 microns (or 4 MIL for heavy duty), often 90-150 GSM.\n* **Sizes**: Customizable; available in widths from 2\" to 200\" and any length, including rolls and sheets.\n* **Colors**: Common options include Blue, Yellow, and Transparent, allowing visibility of contents.\n* **Formats**: Can be supplied as flat bags, gusseted bags, sheets, or rolls.\n* **Printing**: Options for custom printing, often up to 8 colors.\n* **Features**: High strength, good tear resistance, water resistance, and non-toxic/recyclable options.\n\n**Common Applications**:\n* Automotive parts, aerospace components, electronics, machinery, and military equipment.\n\n**How They Work**:\n* VCI molecules vaporize from the bag's surface, filling the enclosed space and creating a thin, invisible film on metal surfaces, stopping the electrochemical corrosion process.",
    price: 35.00,
    categoryId: 'industrial-packaging',
    images: ['/images/vci-new.png'],
    rating: 4.7,
    features: ['75-500 microns thickness', 'Protects ferrous & non-ferrous metals', 'Forms invisible protective film', 'Prevents rust and tarnish'],
    moq: 50,
    uom: 'KGM',
    reviews: []
  },
  {
    id: 'p-vci-polybox',
    name: 'VCI Corrosion Inhibitor Polybox',
    description: 'Specialized packaging designed to protect metal items from rust by releasing anti-corrosive vapors within an enclosed space.',
    longDescription: "A **VCI Polybox** (Volatile Corrosion Inhibitor Polyethylene Box/Bag) is a specialized packaging product designed to protect metal items from rust and corrosion during storage and transport by releasing anti-corrosive vapors within an enclosed space. The term \"Polybox\" often refers to a large, box-shaped or gusseted VCI poly bag designed to line a box or crate.\n\n**Key Specifications & Features**\nSpecifications for VCI Polyboxes can vary by manufacturer and specific application, but generally include the following characteristics:\n* **Material**: Typically manufactured from high-quality virgin resins such as LDPE (Low-Density Polyethylene) or HDPE (High-Density Polyethylene) impregnated with VCI chemicals.\n* **Protection Mechanism**: Releases VCI molecules that vaporize and condense on all exposed metal surfaces, forming a microscopic protective layer that blocks the electrochemical reactions causing corrosion.\n* **Protection Against**: Rust, tarnish, stains, white rust, moisture, condensation, salt, and atmospheric contaminants.\n* **Metals Protected**: Suitable for a variety of ferrous and non-ferrous metals, including carbon steels, cast iron, galvanized steel, stainless steel, aluminum, copper, brass, and silver.\n* **Physical Properties**:\n  * *Thickness*: Commonly available in various thicknesses, ranging from 2.5 mil to 4 mil (approx. 75 to 500 microns), with customizable options.\n  * *Color & Transparency*: Often transparent or tinted (blue, yellow, green) for easy visual inspection of contents without opening the package.\n  * *Strength*: Designed with high tensile strength and tear resistance for durability during shipping and handling.\n* **Shelf Life & Protection Duration**:\n  * *Shelf Life (unopened)*: Up to 12 months when stored in original airtight packaging.\n  * *Protection Duration (in use)*: Provides effective corrosion protection for up to 2–5 years when sealed properly.\n* **Usability & Safety**:\n  * *Ready for Use*: Eliminates the need for applying messy oils or greases, meaning metal parts are ready for use immediately upon removal.\n  * *Safety*: Non-toxic, free of nitrites, phosphates, and heavy metals.\n  * *Environmental*: Recyclable and sometimes available in biodegradable options.\n\n**Available Forms and Styles**\nVCI Polyboxes come in different configurations to suit various packaging needs:\n* Flat bags\n* Gusseted bags (3D/box shape)\n* Perforated bags on rolls\n* Tubing\n* Custom-sized shrouds",
    price: 85.00,
    categoryId: 'industrial-packaging',
    images: ['/images/vci-film.jpg'],
    rating: 4.8,
    features: ['2.5 to 4 mil thickness', 'Protects against rust, stains, moisture', 'Shelf life up to 12 months (unopened)', 'Effective for 2-5 years'],
    moq: 50,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-shrink-film',
    name: 'LDPE Shrink Film',
    description: 'Premium virgin LDPE shrink film providing durable, moisture-resistant packaging with excellent seal integrity.',
    longDescription: "An **LDPE (Low-Density Polyethylene) shrink film specification** details its physical properties like thickness (microns), clarity, shrinkage percentage (MD/TD), and tensile strength, alongside material grade (virgin/prime), density, and application-specific features like perforation or UV resistance, ensuring it provides durable, moisture-resistant packaging with good seal integrity for various products. Key parameters often include density (around 0.922 kg/m³), high elongation, and specific heat shrink temperatures (150-190°C), with thickness varying from 20-100 microns typically.\n\n**Key Specification Parameters**\n* **Material Grade**: Premium Virgin LDPE.\n* **Color/Clarity**: Natural/Transparent (High Clarity).\n* **Thickness**: Commonly 40-80 microns, though can range from 20-150 microns.\n* **Density**: Around 922-930 kg/m³.\n* **Shrinkage**: Machine Direction (MD) 70-80%, Transverse Direction (TD) 15-30% (Biaxial films).\n* **Tensile Strength (MPa)**: MD: 22-30 MPa, TD: 18-25 MPa (varies with thickness).\n* **Elongation at Break**: MD/TD >450%.\n* **Melt Flow Index (MFI)**: Low, e.g., 0.3-0.8 g/10min.\n* **Haze**: Low, <15%.\n* **Slip Coefficient (COF)**: Low (e.g., <0.20 for high slip).\n\n**Common Features & Applications**\n* **Perforations**: Needle perforations to release trapped air during shrinking (for open-end packs).\n* **Sealing**: Can be 3-sided seal or completely closed (bi-axial).\n* **Protection**: Excellent moisture barrier, dust resistance, good protection.\n* **Temperature**: Shrink temperature profile (e.g., 150°C - 190°C).\n* **Applications**: Bundling, product protection for small to large items, attractive packaging.\n\n**Example Specification Snapshot**\n* **Product**: LDPE Biaxial Shrinkable Film, Needle Perforated.\n* **Thickness**: 50 microns (uniform).\n* **Tensile Strength**: MD: 22-30 MPa, TD: 18-25 MPa.\n* **Shrink Ratio**: Specific values (e.g., MD: ~75%, TD: ~20%).\n* **Finish**: Smooth, transparent.",
    price: 55.00,
    categoryId: 'industrial-packaging',
    images: ['/images/ldpe-shrink-film.jpg'],
    rating: 4.6,
    features: ['40-80 microns common thickness', 'MD 70-80% shrinkage', 'Biaxial films', 'Excellent moisture barrier'],
    moq: 100,
    uom: 'KGM',
    reviews: []
  },
  {
    id: 'p-hdpe-bags',
    name: 'Woven HDPE Bags',
    description: 'Strong virgin High-Density Polyethylene bags for fertilizers, chemicals, and heavy materials.',
    longDescription: "**HDPE bag specifications** vary by application (fertilizer, chemicals, etc.) but generally cover material (virgin HDPE, denier, mesh), dimensions (length, width, gusset), weight (GSM), strength (load capacity), construction (stitching, cutting, lamination, printing), and color, often referencing standards like IS 9755. Key details include tape denier (e.g., 1000D), mesh count (e.g., 10x10), GSM (e.g., 100-140 GSM for lighter use, higher for jumbo bags), load capacity (e.g., 25kg, 50kg, 100kg), and features like LDPE lamination or gussets for specific contents.\n\n**Key Specification Parameters**\n* **Material**: Virgin High-Density Polyethylene (HDPE).\n* **Denier**: Tape strength (e.g., 460D to 1600D), often higher for stitching.\n* **Mesh**: Threads per inch (e.g., 8x8 to 14x14).\n* **GSM (Grams per Square Meter)**: Fabric weight (e.g., 48 GSM to 140 GSM for standard, higher for jumbo).\n* **Dimensions**: Width (e.g., 12\" to 48\") and Length (customizable).\n* **Capacity**: Weight the bag holds (e.g., 25kg, 40kg, 50kg, 100kg).\n* **Load Bearing**: Minimum weight it must sustain (e.g., 100kg).\n\n**Construction & Features**\n* **Weaving**: Close weaving, sometimes with specific tape widths (e.g., 2.5mm).\n* **Stitching**: Double-row chain stitch, often with thread denier >20% of fabric tape.\n* **Mouth**: Heat cut, plain, zig-zag, or ultrasonic hem.\n* **Lamination**: Inner LDPE film (e.g., 25-micron) for moisture barrier, as needed.\n* **Gusset**: Side folds (e.g., 2-inch) for shape, if required.\n* **Printing**: Up to 4 colors, corona treated ink, company logo/details.\n* **Color**: White, yellow, or custom colors (e.g., blue tone).\n\n**Standards & Testing**\n* **Standards**: Often conform to Indian Standards (IS) like IS 9755 for fertilizers.\n* **Testing**: May require NABL-accredited lab certificates and third-party inspection.",
    price: 18.50,
    categoryId: 'industrial-packaging',
    images: ['/images/img10.jpeg'],
    rating: 4.7,
    features: ['48-140 GSM fabric weight', 'Double-row chain stitch', 'LDPE inner lamination options', 'High load bearing (25-100kg)'],
    reviews: []
  },
  {
    id: 'p-hdpe-covers',
    name: 'HDPE Covers & Tarpaulins',
    description: 'Durable, waterproof, and UV-stabilized High-Density Polyethylene covers for industrial and agricultural use.',
    longDescription: "**HDPE covers**, typically in the form of tarpaulins, sheets, or manhole covers, are made from High-Density Polyethylene, known for its durability, water resistance, and UV stabilization. Specific product specifications vary based on the intended application (e.g., industrial, agricultural, or civil engineering use).\n\n**General Material Properties**\n* **Material**: High-Density Polyethylene (HDPE), often woven into a fabric and laminated with Low-Density Polyethylene (LDPE) on both sides.\n* **Durability**: Offers excellent tensile strength, tear resistance, and puncture resistance.\n* **Resistance**:\n  * *Waterproof*: 100% waterproof and leak-proof.\n  * *Weatherproof*: Resistant to rot, mildew, and harsh weather conditions.\n  * *Chemical Resistance*: Inert to most chemicals, solvents, acids, and oils.\n  * *UV Resistance*: Typically UV-stabilized to provide protection and a longer life in sunny environments.\n* **Physical**: Lightweight, flexible, non-toxic, and non-staining.\n* **Recyclability**: HDPE is commonly recyclable and has the resin identification code \"2\".\n\n**Common Product Specifications by Type**\n\n*HDPE Tarpaulin/Sheet Covers*\nUsed widely in agriculture, construction, and transportation for covering goods, machinery, and temporary shelters.\n* **Weight (GSM)**: Ranging from 50 GSM to 500 GSM and above, with common options like 120 GSM, 150 GSM, and 250 GSM.\n* **Size**: Available in various standard and customizable sizes (e.g., 17x11 feet, 4x8 feet, 10x10 feet, or large rolls).\n* **Color**: Common colors include blue, green, black, white, silver, and yellow.\n* **Features**: Often includes reinforced edges and rust-proof aluminum or reinforced eyelets at regular intervals for secure tying.\n\n*HDPE Manhole Covers*\nUsed for drainage networks in residential, commercial, and industrial areas.\n* **Load Bearing**: High capacity, designed for light-duty to heavy-duty applications.\n* **Design**: Slip-resistant surface, anti-theft features, and easy lifting mechanisms.\n* **Resistance**: Corrosion-resistant, weatherproof, and UV-stabilized.\n* **Sizes**: Available in various diameters and shapes (e.g., 600x600 mm or 24x24 inches).",
    price: 65.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img4.jpeg'],
    rating: 4.9,
    features: ['100% waterproof', 'UV-stabilized', '50-500 GSM weight range', 'Chemical resistant'],
    reviews: []
  },
  {
    id: 'p-tarpaulin',
    name: 'Heavy Duty Tarpaulin',
    description: 'Heavy gauge multi-layered tarpaulins for covering equipment and goods outdoors. Waterproof and UV-treated.',
    longDescription: "**Tarpaulin specifications** detail material (HDPE, PVC, Canvas), weight (GSM - grams per square meter), thickness, weave (e.g., 28x32), waterproofing, UV resistance, color, and reinforcement (eyelets, hems) for durability, with standards varying by application, from general use (e.g., 170 GSM) to heavy-duty (e.g., 700 GSM PVC) for construction or disaster relief. Key specs include material type, GSM, color, UV treatment, tear strength, and grommet placement.\n\n**Key Specification Categories**\n* **Material**: Common types include Polyethylene (HDPE/LDPE), Polyvinyl Chloride (PVC), Canvas (Cotton/Polyester), or blends, chosen for flexibility, strength, and UV resistance.\n* **Weight (GSM)**: Grams per Square Meter; higher GSM means thicker, heavier, and stronger (e.g., 100-200 GSM light duty, 300+ GSM heavy duty).\n* **Weave & Thickness**: Weave density (e.g., 28x32) and overall thickness (mm) affect strength; multi-layered construction is common.\n* **Waterproofing**: Essential feature, often achieved through PE lamination or PVC coating, ensuring leak-proof performance.\n* **Reinforcement**: Strong hems (stitched edges) and rust-proof eyelets (brass/aluminum) at intervals for tying down.\n* **UV Stabilization**: Important for outdoor use; UV-treated tarps last longer.\n* **Color**: Common colors like blue, green, black, or white (reflective).\n* **Special Features**: Fire retardant (FR) properties, anti-fungal, or specific logos (e.g., UNICEF).\n\n**Example Specifications**\n* **General Purpose HDPE**: 170 GSM, 28x32 weave, blue/black, with eyelets.\n* **Heavy Duty PVC**: 700 GSM, waterproof, fire retardant, for demanding conditions.\n* **UNICEF Plastic Tarp**: 190g/m², white reflective coating, black inner fibers, specific logo placement, high UV resistance.",
    price: 89.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img5.jpeg'],
    rating: 4.9,
    features: ['170 to 700+ GSM options', 'Reinforced hems and eyelets', 'Waterproof & UV stabilized', 'Fire retardant properties (optional)'],
    reviews: []
  },
  {
    id: 'p-bopp-tape-brown',
    name: 'Brown BOPP Packing Tape',
    description: 'Biaxially Oriented Polypropylene film with acrylic or rubber adhesive for strong carton sealing.',
    longDescription: "**BOPP (Biaxially Oriented Polypropylene) Tape** specs vary, but generally include a BOPP film with acrylic/rubber adhesive, common widths like 12-72mm, thicknesses from 35-70 microns (40-50 micron common), and lengths from 25m to 1000m+. Key specs are thickness (strength), width, length, adhesive type (acrylic, rubber), color (clear, brown, colored), core size (usually 76mm), and adhesion strength (tack/peel).\n\n**Typical Specifications**\n* **Material**: BOPP Film with Acrylic or Synthetic Rubber Adhesive.\n* **Thickness**: 35 to 70 microns (µm); common is 40-50µm, heavy-duty up to 70µm.\n* **Width**: 12mm to 72mm (e.g., 1\", 2\", 3\").\n* **Length**: 25m to 4000m (e.g., 65m, 100m, 650m).\n* **Core ID**: 76mm (3 inches).\n* **Color**: Transparent, Brown, or various colors.\n* **Adhesion**: High tack & grip, sticks to paper, plastic, wood, metal, etc.\n\n**Performance & Other Specs**\n* **Holding Power**: Varies by thickness/adhesive (e.g., 7-10+ hours).\n* **Application**: Carton sealing, e-commerce, general packaging.\n* **Features**: Consistent coating, strong grip, durable, long shelf life.\n\n**How to Read a BOPP Tape Spec Sheet**\n* **Look for thickness (µm)**: Higher number means thicker/stronger tape (e.g., 40µm standard, 70µm heavy duty).\n* **Check Width & Length**: Standard roll sizes for packaging.\n* **Note Adhesive Type**: Acrylic offers good clarity and aging; rubber offers strong initial tack.\n* **Check Colors**: Clear for invisible looks, brown for traditional looks, colored for branding/coding.",
    price: 15.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img3.jpeg'],
    rating: 4.6,
    features: ['35 to 70 microns thickness', '25m to 4000m lengths', 'Brown color', 'Strong initial tack & holding power'],
    moq: 10,
    uom: 'BOX',
    reviews: []
  },
  {
    id: 'p-bopp-tape-transparent',
    name: 'Transparent BOPP Packing Tape',
    description: 'Clear Biaxially Oriented Polypropylene film with acrylic adhesive for clean carton sealing.',
    longDescription: "**BOPP (Biaxially Oriented Polypropylene) Tape** specs vary, but generally include a BOPP film with acrylic/rubber adhesive, common widths like 12-72mm, thicknesses from 35-70 microns (40-50 micron common), and lengths from 25m to 1000m+. Key specs are thickness (strength), width, length, adhesive type (acrylic, rubber), color (clear, brown, colored), core size (usually 76mm), and adhesion strength (tack/peel).\n\n**Typical Specifications**\n* **Material**: BOPP Film with Acrylic or Synthetic Rubber Adhesive.\n* **Thickness**: 35 to 70 microns (µm); common is 40-50µm, heavy-duty up to 70µm.\n* **Width**: 12mm to 72mm (e.g., 1\", 2\", 3\").\n* **Length**: 25m to 4000m (e.g., 65m, 100m, 650m).\n* **Core ID**: 76mm (3 inches).\n* **Color**: Transparent, Brown, or various colors.\n* **Adhesion**: High tack & grip, sticks to paper, plastic, wood, metal, etc.\n\n**Performance & Other Specs**\n* **Holding Power**: Varies by thickness/adhesive (e.g., 7-10+ hours).\n* **Application**: Carton sealing, e-commerce, general packaging.\n* **Features**: Consistent coating, strong grip, durable, long shelf life.\n\n**How to Read a BOPP Tape Spec Sheet**\n* **Look for thickness (µm)**: Higher number means thicker/stronger tape (e.g., 40µm standard, 70µm heavy duty).\n* **Check Width & Length**: Standard roll sizes for packaging.\n* **Note Adhesive Type**: Acrylic offers good clarity and aging; rubber offers strong initial tack.\n* **Check Colors**: Clear for invisible looks, brown for traditional looks, colored for branding/coding.",
    price: 15.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img21.jpeg'],
    rating: 4.7,
    features: ['35 to 70 microns thickness', '25m to 4000m lengths', 'Clear color', 'Strong initial tack & holding power'],
    moq: 30,
    uom: 'BOX',
    reviews: []
  },
  {
    id: 'p-pvc-tape',
    name: 'PVC Floor Marking Tape',
    description: 'Plasticized PVC film with high-tack rubber adhesive for marking aisles, hazards, and zones.',
    longDescription: "**PVC Floor Marking Tape specs** include PVC material, rubber-based adhesive, single-sided application, various widths (1\"-6\"+) & lengths (10m, 20m, 30m, 25yd), common colors (yellow, black, red, blue, green, white), and properties like water/solvent resistance, durability, and conformability for marking aisles, hazards, and zones in industrial settings, often with good abrasion resistance for traffic.\n\n**Key Specifications**\n* **Material**: Plasticized PVC Film.\n* **Adhesive**: Rubber-based, pressure-sensitive, high-tack, non-corrosive.\n* **Backing**: PVC.\n* **Sides**: Single-sided.\n* **Colors**: Yellow, Black, Red, Blue, Green, White, Orange, or striped (Yellow/Black, Green/White).\n* **Widths**: Common sizes include 1\", 2\", 3\", 4\", 5\", 6\", 48mm, 72mm, up to 150mm.\n* **Lengths**: Varies by roll, e.g., 10m, 20m, 30m (approx. 33yd), 25 yards.\n* **Thickness**: Around 0.14mm to 0.16mm (± 0.01mm) for standard types, with heavy-duty versions available.\n* **Durability**: Water, solvent, and oil resistant; good abrasion resistance.\n* **Temperature**: Service range around 0°C to +60°C; application +5°C to +40°C.\n* **Compliance**: Often RoHS compliant.\n\n**Features & Applications**\n* **Features**: Easy to apply by hand or machine, forms well to uneven surfaces, UV resistant for outdoor use, leaves minimal residue on removal.\n* **Applications**: Marking traffic lanes, safety zones, work cells, equipment locations, hazard areas (scrap, rework), and dividing spaces in warehouses, factories, and sports facilities.",
    price: 22.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img6.jpeg'],
    rating: 4.4,
    features: ['0.14mm to 0.16mm thickness', 'Water, solvent, and oil resistant', 'Good abrasion resistance', 'Multiple safety colors available'],
    reviews: []
  },
  {
    id: 'p-bubble-wrap',
    name: 'Protective Bubble Wrap (LDPE)',
    description: 'Low-density polyethylene film with air-filled bubbles for shock absorption and protection.',
    longDescription: "**Bubble wrap** is a protective packaging material primarily made of low-density polyethylene (LDPE) film with characteristic air-filled bubbles. Key specifications include bubble size, material thickness (GSM/gauge), and various functional properties like anti-static protection.\n\n**Material Composition**\nBubble wrap is composed primarily of polyethylene resin, often with added components to enhance properties.\n* **Main Material**: Low-density polyethylene (LDPE) film.\n* **Additives**: Other additives can be mixed in to modify properties:\n  * Nylon is sometimes included for added strength and better air retention.\n  * Antistatic agents are used for pink-colored anti-static bubble wrap to dissipate static charges, protecting sensitive electronic components.\n  * Colorants are used to indicate specific types (e.g., green for recycled content) or for custom branding.\n\n**Common Specifications**\nSpecifications vary based on intended use, but several common options are available in the market.\n* **Material**: Polyethylene (PE), specifically LDPE\n* **Bubble Diameter**: Ranges from 6 mm (0.24 inches) to 26 mm (1 inch) or more. Common standard sizes are 1/8\", 3/16\", 5/16\", and 1/2\".\n* **Bubble Height**: Ranges up to 4 mm (small bubble) to 7 mm or more (large bubble).\n* **Film Thickness**: Often measured in Gauge (e.g., 400 gauge) or GSM (grams per square meter), with common ranges like 40 GSM to 80 GSM for standard rolls.\n* **Roll Dimensions**: Typically available in widths of 0.5 meters, 1 meter, 1.2 meters, and 1.5 meters, with lengths often in 50m or 100m rolls.\n* **Properties**: Lightweight, moisture-resistant, shock-absorbent, buoyant, and reusable.\n\n**Specialized Types**\n* **Anti-Static Bubble Wrap**: Colored pink and designed to prevent static charge buildup, essential for packaging electronics.\n* **Heavy-Duty**: Features thicker film and/or larger, more durable bubbles for enhanced protection against drops and impacts.",
    price: 28.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img27.jpeg'],
    rating: 4.8,
    isFeatured: true,
    features: ['Small to large bubbles (6-26mm)', '40 to 80 GSM standard thickness', 'Anti-static variants available', 'Lightweight and moisture-resistant'],
    reviews: []
  },
  {
    id: 'p-cross-lamination',
    name: 'Cross Laminated Panels',
    description: 'Cross-laminated materials providing enhanced dimensional stability, strength, and rigidity.',
    longDescription: "**Cross-lamination** is a manufacturing technique that involves layering materials, such as timber or polymers, with the orientation of each layer perpendicular (typically 90 degrees) to the adjacent layers to enhance dimensional stability, strength, and rigidity. The resulting product, such as Cross-Laminated Timber (CLT), has specific technical specifications related to dimensions, material properties, and performance.\n\n**General Product Specifications**\n* **Layer Orientation**: Adjacent layers are typically oriented at 90-degree angles to each other, which provides structural rigidity in both directions.\n* **Layers**: Products commonly consist of an odd number of layers (e.g., 3, 5, 7, or 9) to maintain symmetry, ensuring the outer layers have the same orientation.\n* **Adhesives**: Structural adhesives such as phenol-resorcinol formaldehyde (PRF), one-component polyurethane (PUR), or emulsion polymer isocyanate (EPI) are used for bonding. The adhesive bond should be stronger than the material itself, leading to wood failure rather than glue-line failure during testing.\n* **Dimensional Stability**: The cross-lamination process significantly improves dimensional stability and minimizes shrinking and swelling from moisture variations, compared to solid wood.\n* **Anisotropy Reduction**: By cross-laminating, the material's properties become more uniform across the panel, mitigating the natural anisotropy of the base material (e.g., wood).\n\n**Cross-Laminated Timber (CLT) Specifics**\nCLT is a common application of this principle in construction, with the following technical specifications:\n* **Material**: Made from solid-sawn lumber boards, typically softwood species like spruce, pine, and fir, which are kiln-dried to a moisture content of around 10-15%.\n* **Dimensions**: Panels can be manufactured in large sizes, with widths up to 3.5 m and lengths up to 18 m or more. Thicknesses typically range from 60 mm to 360 mm, depending on structural requirements.\n* **Strength and Performance**:\n  * *High Strength-to-Weight Ratio*: It is lighter than concrete and steel but offers comparable strength, reducing foundation costs.\n  * *Fire Resistance*: CLT performs well in fires due to a predictable charring rate (approx. 0.7 mm/min), which insulates the inner layers and helps maintain load-bearing capacity for extended periods (e.g., REI 90 or 120 ratings).\n  * *Acoustic Properties*: Provides good sound insulation characteristics, comparable to other construction methods when combined with appropriate systems like suspended ceilings or floor screeds.\n  * *Thermal Performance*: Wood's low thermal conductivity (around 0.13 W/mK) makes CLT a good insulator, aiding in energy efficiency.\n\n**Product Standards and Certifications**\nProducts such as CLT must comply with industry standards to ensure quality and reliability. Relevant standards include ANSI/APA PRG 320 (North America) and EN 16351 (Europe). These standards define requirements for aspects such as:\n* **Moisture Content**: Specified range for the base material during manufacturing.\n* **Adhesive Bonding**: Testing requirements for block shear strength and delamination percentage under various conditions.\n* **Dimensional Tolerances**: Permissible variations in thickness, width, length, squareness, and straightness of the final product.\n* **Strength Grading**: The lumber used must meet specific strength classes (e.g., EN 338 ≥ C16).",
    price: 150.00,
    categoryId: 'industrial-packaging',
    images: ['/images/img7.jpeg'],
    rating: 4.8,
    features: ['90-degree layer orientation', 'High strength-to-weight ratio', 'Excellent dimensional stability', 'Reduced anisotropy'],
    reviews: []
  },

  // Sales & Growth Automation
  {
    id: 'p-ai-pitch-engine',
    name: 'AI Pitch Engine',
    description: 'Generate personalized, high-converting sales pitches instantly.',
    longDescription: '**AI Pitch Engine** uses advanced language models to generate hyper-personalized sales pitches based on prospect data, industry trends, and your product value proposition.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'sales-growth-automation',
    images: ['/images/img9.jpeg'],
    rating: 4.8,
    isFeatured: true,
    features: ['Personalization at scale', 'CRM Integration', 'A/B Testing'],
    moq: 1,
    uom: 'License',
    reviews: []
  },
  {
    id: 'p-marketing-ai-agent',
    name: 'Marketing AI Agent',
    description: 'Autonomous agent that manages and optimizes ad campaigns across channels.',
    longDescription: 'Deploy our **Marketing AI Agent** to continuously monitor, adjust, and optimize your digital ad spending across Google, Facebook, and LinkedIn for maximum ROI.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'sales-growth-automation',
    images: ['/images/img29.jpeg'],
    rating: 4.7,
    features: ['Cross-channel optimization', 'Budget reallocation', 'Creative generation'],
    moq: 1,
    uom: 'License',
    reviews: []
  },
  {
    id: 'p-linkedin-lead',
    name: 'LinkedIn Lead Intelligence',
    description: 'Scrape, enrich, and score LinkedIn leads automatically.',
    longDescription: 'Automate your outbound prospecting with **LinkedIn Lead Intelligence**. Extract clean data, enrich it with contact info, and score leads based on buying intent signals.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'sales-growth-automation',
    images: ['/images/img16.jpeg'],
    rating: 4.9,
    features: ['Automated scraping', 'Email enrichment', 'Intent scoring'],
    moq: 1,
    uom: 'Instance',
    reviews: []
  },
  {
    id: 'p-contact-library',
    name: 'Contact Library',
    description: 'Access millions of verified B2B contacts and decision-makers.',
    longDescription: 'Stop wasting time on bad data. The **Contact Library** gives your sales team direct access to verified B2B emails and direct dials across major global industries.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'sales-growth-automation',
    images: ['/images/img26.jpeg'],
    rating: 4.5,
    features: ['Millions of records', 'Real-time verification', 'Direct dials'],
    moq: 1,
    uom: 'Subscription',
    reviews: []
  },
  {
    id: 'p-wa-sales-agent',
    name: 'WhatsApp Business AI Agent',
    description: 'Engage inbound leads instantly on WhatsApp and book meetings automatically.',
    longDescription: 'Never miss a lead again. Our **WhatsApp Business AI Agent** qualifies inbound inquiries in real-time and books meetings directly into your sales team calendar.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'sales-growth-automation',
    images: ['/images/img12.jpeg'],
    rating: 4.8,
    features: ['24/7 engagement', 'Calendar integration', 'Natural language processing'],
    moq: 1,
    uom: 'Bot',
    reviews: []
  },
  // Procurement & Supply Chain Intelligence
  {
    id: 'p-procurement-ai',
    name: 'Procurement AI Agent',
    description: 'Automate PO processing and vendor negotiations.',
    longDescription: 'The **Procurement AI Agent** streamlines your purchasing department by automatically matching invoices, issuing POs, and negotiating baseline terms with standard vendors.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'procurement-supply-chain-ai',
    images: ['/images/img19.jpeg'],
    rating: 4.6,
    isFeatured: true,
    features: ['Automated PO matching', 'Vendor portal', 'Spend analytics'],
    moq: 1,
    uom: 'Platform',
    reviews: []
  },
  {
    id: 'p-supplier-intel',
    name: 'Supplier Intelligence Platform',
    description: 'Monitor supplier risk, compliance, and performance in real-time.',
    longDescription: 'Gain end-to-end visibility into your supply chain. The **Supplier Intelligence Platform** uses AI to monitor geopolitical risks, compliance documentation, and on-time delivery metrics.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'procurement-supply-chain-ai',
    images: ['/images/img1.jpeg'],
    rating: 4.9,
    features: ['Risk scoring', 'Compliance tracking', 'Alternative sourcing'],
    moq: 1,
    uom: 'Platform',
    reviews: []
  },
  // Content & Creative AI
  {
    id: 'p-clipcraftai',
    name: 'ClipCraftAI',
    description: 'Turn long-form videos into viral shorts automatically.',
    longDescription: '**ClipCraftAI** analyzes podcasts and webinars to find the most engaging moments, automatically framing speakers, adding bold captions, and exporting ready-to-post short-form video.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'content-creative-ai',
    images: ['/images/img18.jpg'],
    rating: 4.7,
    features: ['Auto-framing', 'Dynamic captions', 'Trend detection'],
    moq: 1,
    uom: 'License',
    reviews: []
  },
  {
    id: 'p-typomotion-ai',
    name: 'TypoMotion AI',
    description: 'Generate stunning kinetic typography videos from text.',
    longDescription: 'With **TypoMotion AI**, type in your script and instantly receive a fully animated, dynamic kinetic typography video synced perfectly to AI-generated voiceovers.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'content-creative-ai',
    images: ['/images/img11.png'],
    rating: 4.8,
    features: ['Text-to-animation', 'Custom fonts', 'Lip-syncing audio'],
    moq: 1,
    uom: 'License',
    reviews: []
  },
  {
    id: 'p-ai-content-studio',
    name: 'AI Content Studio',
    description: 'All-in-one platform for blogs, SEO, and social media generation.',
    longDescription: 'The **AI Content Studio** helps marketers research keywords, outline articles, and draft high-ranking SEO content that matches your unique brand voice.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'content-creative-ai',
    images: ['/images/img17.jpeg'],
    rating: 4.9,
    features: ['SEO optimization', 'Brand voice adaptation', 'Multi-channel publishing'],
    moq: 1,
    uom: 'Platform',
    reviews: []
  },
  // Customer Experience & Support
  {
    id: 'p-wa-support-agent',
    name: 'WhatsApp Business AI Agent',
    description: 'Deliver instant support and issue resolution over WhatsApp.',
    longDescription: 'Turn WhatsApp into your primary support channel. The **WhatsApp Business AI Agent** resolves common queries instantly, handles returns, and escalates complex issues to human agents.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'customer-experience-support',
    images: ['/images/img8.jpeg'],
    rating: 4.8,
    features: ['Instant replies', 'Ticket escalation', 'Multi-language'],
    moq: 1,
    uom: 'Bot',
    reviews: []
  },
  {
    id: 'p-ai-chatbots',
    name: 'AI Chatbots',
    description: 'Deploy intelligent chatbots on your website or app.',
    longDescription: 'Embed powerful **AI Chatbots** directly into your site. Trained on your own help center data, these bots eliminate wait times and reduce support ticket volume by up to 70%.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'customer-experience-support',
    images: ['/images/img2.jpeg'],
    rating: 4.5,
    features: ['Custom UI', 'Knowledge base sync', 'Human handoff'],
    moq: 1,
    uom: 'Bot',
    reviews: []
  },
  {
    id: 'p-customer-support-agent',
    name: 'Customer Support Agent',
    description: 'Autonomous agent that resolves complex support tickets via email.',
    longDescription: 'The **Customer Support Agent** reads incoming emails, analyzes sentiment, searches your database for solutions, and drafts highly accurate replies to complex support queries.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'customer-experience-support',
    images: ['/images/img31.jpg'],
    rating: 4.9,
    features: ['Zendesk integration', 'Sentiment analysis', 'Automated refunds'],
    moq: 1,
    uom: 'Agent',
    reviews: []
  },
  {
    id: 'p-wa-order-agent',
    name: 'WhatsApp Order Agent',
    description: 'Allow customers to browse catalogs and place orders directly in WhatsApp.',
    longDescription: 'Transform WhatsApp into a storefront. The **WhatsApp Order Agent** provides an interactive catalog, processes payments, and sends real-time shipping updates without the customer ever leaving the chat app.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'customer-experience-support',
    images: ['/images/img30.jpeg'],
    rating: 4.7,
    features: ['Catalog integration', 'Payment gateway sync', 'Order tracking'],
    moq: 1,
    uom: 'Agent',
    reviews: []
  },
  // Knowledge & Enterprise AI
  {
    id: 'p-enterprise-rag',
    name: 'Enterprise RAG Knowledge Assistant',
    description: 'Chat with your company data securely using Retrieval-Augmented Generation.',
    longDescription: 'The **Enterprise RAG Knowledge Assistant** ingests your internal wikis, Google Drives, and Slack histories, allowing employees to ask questions and get cited answers securely, without model hallucination.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'knowledge-enterprise-ai',
    images: ['/images/img14.jpeg'],
    rating: 5.0,
    features: ['Secure data silos', 'Multi-format support', 'Citation generation'],
    moq: 1,
    uom: 'System',
    reviews: []
  },
  {
    id: 'p-doc-intel',
    name: 'Document Intelligence Platform',
    description: 'Extract and process structured data from complex unstructured documents.',
    longDescription: 'Automate data entry with the **Document Intelligence Platform**. Our OCR and text-extraction AI pulls critical fields from messy PDFs, invoices, and hand-written forms with near-perfect accuracy.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'knowledge-enterprise-ai',
    images: ['/images/img24.jpeg'],
    rating: 4.8,
    features: ['OCR', 'Entity extraction', 'Table parsing'],
    moq: 1,
    uom: 'Platform',
    reviews: []
  },
  // Custom AI Development
  {
    id: 'p-custom-ai-agent',
    name: 'Custom AI Agent Development',
    description: 'Tailor-made AI agents built to execute your specific business workflows.',
    longDescription: 'Need something unique? Our engineering team provides **Custom AI Agent Development**, crafting specialized models and agents designed exclusively for your niche operational workflows.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'custom-ai-development',
    images: ['/images/img23.jpeg'],
    rating: 4.9,
    features: ['Custom logic', 'API integrations', 'Dedicated support'],
    moq: 1,
    uom: 'Project',
    reviews: []
  },
  {
    id: 'p-multi-agent',
    name: 'Multi-Agent Systems',
    description: 'Complex operational flows managed by interacting specialized AI agents.',
    longDescription: 'Deploy **Multi-Agent Systems** where different AI models (like a researcher, a writer, and an editor) interact, debate, and sequentially execute complex tasks autonomously.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'custom-ai-development',
    images: ['/images/img28.jpeg'],
    rating: 5.0,
    features: ['Agent orchestration', 'Conflict resolution', 'High autonomy'],
    moq: 1,
    uom: 'Project',
    reviews: []
  },
  {
    id: 'p-enterprise-auto',
    name: 'Enterprise Automation Solutions',
    description: 'End-to-end AI transformation for large-scale enterprise operations.',
    longDescription: 'Our flagship service, **Enterprise Automation Solutions**, maps out your entire legacy operational flow and systematically upgrades it using state-of-the-art AI tooling and predictive models.',
    price: 0,
    isContactForPrice: true,
    categoryId: 'custom-ai-development',
    images: ['/images/img20.jpeg'],
    rating: 4.8,
    features: ['Legacy migration', 'Workflow mapping', 'ROI tracking'],
    moq: 1,
    uom: 'Deployment',
    reviews: []
  },

  // Electronics - PCs, GPUs, Cameras with AI Integration
  {
    id: 'p-kalika-gaming-pc-4070ti',
    name: 'Kalika AI Gaming Desktop PC - RTX 4070 Ti Super',
    description: 'High-performance gaming PC with integrated AI upscaling (DLSS 3.5), AI noise cancellation, and smart performance optimization.',
    longDescription: '**Kalika AI Gaming PC** combines cutting-edge hardware with intelligent AI features. Powered by NVIDIA RTX 4070 Ti Super with DLSS 3.5 for AI-accelerated graphics, this system delivers unparalleled gaming and creative performance.\n\n**AI Features:**\n- NVIDIA DLSS 3.5 AI Upscaling\n- AI Noise Cancellation for voice chat\n- Smart Performance Boost\n- AI Overclocking\n\n**Specifications:**\n- GPU: NVIDIA RTX 4070 Ti Super 16GB\n- CPU: Intel Core i7-14700K\n- RAM: 32GB DDR5 5600MHz\n- Storage: 1TB NVMe Gen4 SSD\n- Motherboard: Z790 ATX\n- PSU: 850W 80+ Gold\n- Cooling: 240mm AIO Liquid\n- Case: Mid Tower RGB',
    price: 185000,
    discountedPrice: 166500,
    discountPercent: 10,
    categoryId: 'electronics-gaming-pc',
    images: ['/images/img15.jpeg'],
    rating: 4.9,
    isFeatured: true,
    features: ['NVIDIA DLSS 3.5', 'AI Noise Cancellation', 'Smart Performance Boost', 'AI Overclocking', '32GB DDR5', '1TB NVMe Gen4'],
    aiFeatures: ['NVIDIA DLSS 3.5', 'AI Noise Cancellation', 'Smart Performance Boost', 'AI Overclocking'],
    specifications: { gpu: 'NVIDIA RTX 4070 Ti Super 16GB', cpu: 'Intel Core i7-14700K', ram: '32GB DDR5 5600MHz', storage: '1TB NVMe Gen4 SSD' },
    packagingOptions: ['standard', 'custom_box', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: [
      { id: 'r-pc1', userName: 'Gamer Pro', rating: 5, comment: 'Best AI gaming PC I have used. DLSS 3.5 is incredible.', date: '2024-08-15' },
      { id: 'r-pc2', userName: 'Content Creator', rating: 5, comment: 'Perfect for video editing and gaming combo.', date: '2024-09-01' }
    ]
  },
  {
    id: 'p-kalika-workstation-pc-4090',
    name: 'Kalika AI Workstation PC - RTX 4090 Creative Pro',
    description: 'Professional workstation with AI-accelerated rendering, smart resource allocation, and enterprise-grade reliability.',
    longDescription: '**Kalika AI Workstation** is built for professionals who demand the best. With NVIDIA RTX 4090 and AI-powered rendering, this workstation transforms creative workflows.\n\n**AI Features:**\n- AI Render Acceleration\n- Smart Resource Manager\n- AI Color Grading\n- Neural Engine for ML workloads\n\n**Specifications:**\n- GPU: NVIDIA RTX 4090 24GB\n- CPU: Intel Core i9-14900K\n- RAM: 64GB DDR5 5600MHz\n- Storage: 2TB NVMe Gen4 SSD + 4TB HDD\n- Motherboard: Z790 ATX Workstation\n- PSU: 1000W 80+ Platinum\n- Cooling: 360mm AIO Liquid\n- Case: Full Tower E-ATX',
    price: 345000,
    discountedPrice: 310500,
    discountPercent: 10,
    categoryId: 'electronics-workstation-pc',
    images: ['/images/img20.jpeg'],
    rating: 4.9,
    isFeatured: true,
    features: ['AI Render Acceleration', 'Smart Resource Manager', 'AI Color Grading', 'Neural Engine', '64GB DDR5', 'RTX 4090 24GB'],
    aiFeatures: ['AI Render Acceleration', 'Smart Resource Manager', 'AI Color Grading', 'Neural Engine'],
    specifications: { gpu: 'NVIDIA RTX 4090 24GB', cpu: 'Intel Core i9-14900K', ram: '64GB DDR5 5600MHz', storage: '2TB NVMe + 4TB HDD' },
    packagingOptions: ['standard', 'custom_box', 'stretch_film', 'vci'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-budget-pc-4060',
    name: 'Kalika Budget AI PC - RTX 4060 Smart Entry',
    description: 'Affordable AI-powered PC for everyday use with intelligent task management and AI-enhanced multimedia.',
    longDescription: '**Kalika Budget AI PC** brings AI capabilities to everyday computing. Perfect for students, professionals, and casual gamers.\n\n**AI Features:**\n- AI Task Manager\n- Smart Power Save\n- AI Photo Enhancement\n\n**Specifications:**\n- GPU: NVIDIA RTX 4060 8GB\n- CPU: Intel Core i5-14400F\n- RAM: 16GB DDR5 4800MHz\n- Storage: 512GB NVMe SSD\n- Motherboard: B760 mATX\n- PSU: 650W 80+ Bronze\n- Cooling: Tower Cooler\n- Case: mATX Compact',
    price: 72000,
    discountedPrice: 64800,
    discountPercent: 10,
    categoryId: 'electronics-budget-pc',
    images: ['/images/img15.jpeg'],
    rating: 4.7,
    features: ['AI Task Manager', 'Smart Power Save', 'AI Photo Enhancement', '16GB DDR5', 'RTX 4060 8GB'],
    aiFeatures: ['AI Task Manager', 'Smart Power Save', 'AI Photo Enhancement'],
    specifications: { gpu: 'NVIDIA RTX 4060 8GB', cpu: 'Intel Core i5-14400F', ram: '16GB DDR5 4800MHz', storage: '512GB NVMe SSD' },
    packagingOptions: ['standard', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-nvidia-rtx4090-oc',
    name: 'NVIDIA GeForce RTX 4090 24GB OC - Kalika Edition',
    description: 'Flagship GPU with AI-powered DLSS 3.5, ray tracing, and neural rendering. Kalika custom cooling.',
    longDescription: '**NVIDIA RTX 4090 Kalika Edition** - The ultimate GPU for AI-accelerated gaming and content creation.\n\n**AI Features:**\n- DLSS 3.5 AI Upscaling\n- Ray Tracing with AI denoising\n- Neural Rendering\n- AI Noise Cancel for streaming\n\n**Specifications:**\n- Memory: 24GB GDDR6X\n- Boost Clock: 2520 MHz\n- CUDA Cores: 16384\n- Tensor Cores: 5th Gen\n- RT Cores: 3rd Gen\n- Power: 450W TDP\n- Interface: PCIe 4.0 x16',
    price: 210000,
    discountedPrice: 189000,
    discountPercent: 10,
    categoryId: 'electronics-gpu',
    images: ['/images/img15.jpeg'],
    rating: 4.9,
    isFeatured: true,
    features: ['DLSS 3.5', 'Ray Tracing', 'Neural Rendering', '24GB GDDR6X', '16384 CUDA Cores'],
    aiFeatures: ['DLSS 3.5', 'Ray Tracing', 'Neural Rendering', 'AI Noise Cancel'],
    specifications: { memory: '24GB GDDR6X', boost_clock: '2520 MHz', cuda_cores: '16384', power: '450W TDP' },
    packagingOptions: ['standard', 'anti_static', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-nvidia-rtx4070ti-super',
    name: 'NVIDIA GeForce RTX 4070 Ti Super 16GB - Kalika Tuned',
    description: 'High-end GPU with AI upscaling and content creation acceleration. Factory overclocked.',
    longDescription: '**NVIDIA RTX 4070 Ti Super Kalika Tuned** - Premium performance for gamers and creators.\n\n**AI Features:**\n- DLSS 3.5\n- AV1 Encode for streaming\n- AI Photo Enhance\n- Smart Resolution scaling\n\n**Specifications:**\n- Memory: 16GB GDDR6X\n- Boost Clock: 2640 MHz\n- CUDA Cores: 8448\n- Tensor Cores: 4th Gen\n- RT Cores: 3rd Gen\n- Power: 285W TDP',
    price: 82000,
    discountedPrice: 73800,
    discountPercent: 10,
    categoryId: 'electronics-gpu',
    images: ['/images/img15.jpeg'],
    rating: 4.8,
    isFeatured: true,
    features: ['DLSS 3.5', 'AV1 Encode', 'AI Photo Enhance', '16GB GDDR6X', 'Factory Overclocked'],
    aiFeatures: ['DLSS 3.5', 'AV1 Encode', 'AI Photo Enhance', 'Smart Resolution'],
    specifications: { memory: '16GB GDDR6X', boost_clock: '2640 MHz', cuda_cores: '8448', power: '285W TDP' },
    packagingOptions: ['standard', 'anti_static', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-nvidia-rtx4060',
    name: 'NVIDIA GeForce RTX 4060 8GB - Kalika Smart',
    description: 'Entry-level AI GPU for 1080p gaming and AI applications. Budget-friendly.',
    longDescription: '**NVIDIA RTX 4060 Kalika Smart** - Entry point to AI-powered gaming.\n\n**AI Features:**\n- DLSS 3\n- AV1 Encode\n- AI Background Blur for calls\n\n**Specifications:**\n- Memory: 8GB GDDR6\n- Boost Clock: 2460 MHz\n- CUDA Cores: 3072\n- Power: 115W TDP',
    price: 32000,
    discountedPrice: 28800,
    discountPercent: 10,
    categoryId: 'electronics-gpu',
    images: ['/images/img15.jpeg'],
    rating: 4.7,
    features: ['DLSS 3', 'AV1 Encode', 'AI Background Blur', '8GB GDDR6', 'Low Power'],
    aiFeatures: ['DLSS 3', 'AV1 Encode', 'AI Background Blur'],
    specifications: { memory: '8GB GDDR6', boost_clock: '2460 MHz', cuda_cores: '3072', power: '115W TDP' },
    packagingOptions: ['standard', 'anti_static'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-cinema-camera',
    name: 'Kalika AI Pro Camera System - 4K Cinema Kit',
    description: 'Professional cinema camera with AI auto-focus, scene detection, and intelligent color grading.',
    longDescription: '**Kalika AI Cinema Camera** - Hollywood-grade technology for creators.\n\n**AI Features:**\n- AI Auto-Focus with eye tracking\n- Scene Detection for auto settings\n- AI Color Grading\n- Smart Stabilization\n- Voice Control\n\n**Specifications:**\n- Sensor: Full Frame 45MP CMOS\n- Video: 8K 30fps, 4K 120fps\n- ISO: 100-51200\n- Autofocus: 1053 AF Points AI\n- Stabilization: 5-axis IBIS\n- Connectivity: WiFi 6E, Bluetooth 5.3',
    price: 485000,
    discountedPrice: 436500,
    discountPercent: 10,
    categoryId: 'electronics-camera',
    images: ['/images/img18.jpg'],
    rating: 4.9,
    isFeatured: true,
    features: ['AI Auto-Focus', 'Scene Detection', 'AI Color Grading', '8K Video', '5-axis IBIS', 'Voice Control'],
    aiFeatures: ['AI Auto-Focus', 'Scene Detection', 'AI Color Grading', 'Smart Stabilization', 'Voice Control'],
    specifications: { sensor: 'Full Frame 45MP CMOS', video: '8K 30fps, 4K 120fps', iso: '100-51200', autofocus: '1053 AF Points AI' },
    packagingOptions: ['standard', 'custom_box', 'vci', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-security-camera',
    name: 'Kalika AI Security Camera System - 8 Channel NVR',
    description: 'Smart security system with AI person detection, facial recognition, and automated alerts.',
    longDescription: '**Kalika AI Security System** - Enterprise-grade surveillance with AI.\n\n**AI Features:**\n- AI Person Detection\n- Facial Recognition\n- Smart Alerts\n- License Plate Recognition\n- Behavior Analysis\n\n**Specifications:**\n- Resolution: 4K Ultra HD\n- Channels: 8 Channel NVR\n- Cameras: 4x 4K Turret\n- Night Vision: 30m Color\n- Storage: 4TB HDD Included\n- Mobile App: Kalika Vision AI',
    price: 65000,
    discountedPrice: 58500,
    discountPercent: 10,
    categoryId: 'electronics-security',
    images: ['/images/img8.jpeg'],
    rating: 4.8,
    isFeatured: true,
    features: ['AI Person Detection', 'Facial Recognition', '4K Resolution', 'Smart Alerts', 'License Plate Recognition'],
    aiFeatures: ['AI Person Detection', 'Facial Recognition', 'Smart Alerts', 'License Plate Recognition', 'Behavior Analysis'],
    specifications: { resolution: '4K Ultra HD', channels: '8 Channel NVR', night_vision: '30m Color Night Vision', storage: '4TB HDD Included' },
    packagingOptions: ['standard', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-webcam-pro',
    name: 'Kalika AI Webcam Pro - 4K Streaming with AI Background',
    description: '4K webcam with AI background blur, auto-framing, and noise cancellation.',
    longDescription: '**Kalika AI Webcam Pro** - Professional streaming meets AI.\n\n**AI Features:**\n- AI Background Blur\n- Auto-Framing\n- Noise Cancellation\n- Auto Exposure\n\n**Specifications:**\n- Resolution: 4K 30fps / 1080p 60fps\n- FOV: 90 degrees\n- Microphone: Dual Array AI Noise Cancel\n- Autofocus: AI Face Tracking\n- Low Light: AI HDR\n- Connectivity: USB-C',
    price: 12000,
    discountedPrice: 10800,
    discountPercent: 10,
    categoryId: 'electronics-webcam',
    images: ['/images/img2.jpeg'],
    rating: 4.7,
    features: ['AI Background Blur', 'Auto-Framing', 'Noise Cancellation', '4K Resolution', 'AI HDR'],
    aiFeatures: ['AI Background Blur', 'Auto-Framing', 'Noise Cancellation', 'Auto Exposure'],
    specifications: { resolution: '4K 30fps / 1080p 60fps', fov: '90 degrees', microphone: 'Dual Array AI Noise Cancel', connectivity: 'USB-C' },
    packagingOptions: ['standard', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-gaming-monitor',
    name: 'Kalika AI Gaming Monitor - 27" 4K 144Hz OLED',
    description: 'Premium gaming monitor with AI upscaling, adaptive sync, and smart brightness.',
    longDescription: '**Kalika AI Gaming Monitor** - See AI in every pixel.\n\n**AI Features:**\n- AI Upscaling\n- Smart HDR\n- Adaptive Sync Pro\n- Eye Care AI\n\n**Specifications:**\n- Size: 27 inch\n- Panel: WOLED\n- Resolution: 3840x2160\n- Refresh Rate: 144Hz\n- Response Time: 0.1ms GTG\n- HDR: HDR10+ / Dolby Vision\n- Color: 99% DCI-P3',
    price: 95000,
    discountedPrice: 85500,
    discountPercent: 10,
    categoryId: 'electronics-monitor',
    images: ['/images/img15.jpeg'],
    rating: 4.8,
    isFeatured: true,
    features: ['AI Upscaling', 'Smart HDR', 'OLED Panel', '144Hz', '0.1ms Response', '99% DCI-P3'],
    aiFeatures: ['AI Upscaling', 'Smart HDR', 'Adaptive Sync Pro', 'Eye Care AI'],
    specifications: { size: '27 inch', panel: 'WOLED', resolution: '3840x2160', refresh_rate: '144Hz' },
    packagingOptions: ['standard', 'custom_box', 'stretch_film'],
    moq: 1,
    uom: 'NOS',
    reviews: []
  },
  {
    id: 'p-kalika-smart-office-bundle',
    name: 'Kalika Smart Office AI Bundle - PC + Camera + Monitor',
    description: 'Complete AI-powered office solution with intelligent PC, security camera, and smart monitor.',
    longDescription: '**Kalika Smart Office Bundle** - Everything your office needs, AI-powered.\n\n**Bundle Includes:**\n- Kalika AI Workstation PC\n- Security Camera System (8 Channel)\n- 4K 144Hz OLED Monitor\n\n**AI Features:**\n- AI Office Assistant\n- Smart Security\n- Auto-Optimization\n- Voice Control\n- Energy Management\n\n**Bonus:**\n- Kalika AI Suite 1 Year License\n- 24/7 Priority Support\n- Free On-Site Setup',
    price: 320000,
    discountedPrice: 272000,
    discountPercent: 15,
    categoryId: 'electronics-ai-bundle',
    images: ['/images/img20.jpeg'],
    rating: 4.9,
    isFeatured: true,
    features: ['Complete Office Setup', 'AI Office Assistant', 'Smart Security', '15% Bundle Discount', 'Free Setup', '1 Year AI Suite'],
    aiFeatures: ['AI Office Assistant', 'Smart Security', 'Auto-Optimization', 'Voice Control', 'Energy Management'],
    specifications: { includes: 'Workstation + Security Camera + Monitor', software: 'Kalika AI Suite 1 Year', support: '24/7 Priority', installation: 'Free On-Site' },
    packagingOptions: ['custom_box', 'stretch_film', 'vci'],
    moq: 1,
    uom: 'Bundle',
    reviews: []
  },
  {
    id: 'p-kalika-creator-bundle',
    name: 'Kalika Content Creator AI Bundle - PC + Camera + Webcam',
    description: 'Complete AI-powered content creation suite for YouTubers and streamers.',
    longDescription: '**Kalika Creator Bundle** - Your content creation dream team.\n\n**Bundle Includes:**\n- Kalika AI Workstation PC (RTX 4090)\n- Cinema Camera 4K Kit\n- Webcam Pro\n\n**AI Features:**\n- AI Video Editing\n- Smart Scene Detection\n- Auto Color Grading\n- Noise Cancellation\n- Stream Overlay AI\n\n**Bonus:**\n- Kalika Creator Suite 1 Year License\n- Priority Creator Support\n- Free 1-on-1 Setup Session',
    price: 550000,
    discountedPrice: 467500,
    discountPercent: 15,
    categoryId: 'electronics-ai-bundle',
    images: ['/images/img18.jpg'],
    rating: 4.9,
    isFeatured: true,
    features: ['Complete Creator Setup', 'AI Video Editing', '15% Bundle Discount', 'Free Setup Session', '1 Year Creator Suite'],
    aiFeatures: ['AI Video Editing', 'Smart Scene Detection', 'Auto Color Grading', 'Noise Cancellation', 'Stream Overlay AI'],
    specifications: { includes: 'Workstation + Cinema Camera + Webcam', software: 'Kalika Creator Suite 1 Year', support: 'Priority Creator Support', training: 'Free 1-on-1 Setup' },
    packagingOptions: ['custom_box', 'stretch_film', 'vci'],
    moq: 1,
    uom: 'Bundle',
    reviews: []
  }
];

